import "./globals.css";
import Head from "next/head";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "AnvetCard Template",
  description: "Generated by Anvetcorp SAS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* SEO Meta Tags */}
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="title" content={metadata.title} />
        <meta name="description" content={metadata.description} />
        <meta name="keywords" content="Coac SUP Ltda, credit cooperative, loans, savings, financial services" />
        <meta name="author" content="Anvetcorp SAS" />
        <meta name="robots" content="index, follow" />

        {/* Open Graph Meta Tags */}
        <meta property="og:title" content={metadata.title} />
        <meta property="og:description" content={metadata.description} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.coacsup.com/" />
        <meta property="og:image" content="/assets/images/logo.png" />

        {/* Twitter Meta Tags */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={metadata.title} />
        <meta name="twitter:description" content={metadata.description} />
        <meta name="twitter:image" content="/assets/images/logo.png" />

        {/* Favicon */}
        <link rel="icon" href="/public/assets/icons/favicon.ico" type="image/x-icon" />
        
        {/* Fonts Preconnection */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Lato:wght@400;700&display=swap"
          rel="stylesheet"
        />

        {/* Title */}
        <title>{metadata.title}</title>
      </Head>
      <body className="bg-image-with-overlay">
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
